export const AUDIT_ACTIONS = {
  OTP_VIEWED: "OTP_VIEWED",
  OTP_BLOCKED: "OTP_BLOCKED",
  ACCESS_REQUEST_SUBMITTED: "ACCESS_REQUEST_SUBMITTED",
  REQUEST_APPROVED: "REQUEST_APPROVED",
  REQUEST_REJECTED: "REQUEST_REJECTED",
  USER_CREATED: "USER_CREATED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_BY_ADMIN: "PASSWORD_RESET_BY_ADMIN",
  USER_DISABLED: "USER_DISABLED",
  USER_ENABLED: "USER_ENABLED",
  USER_DELETED: "USER_DELETED",
  MANUAL_VIEW_ADJUSTMENT: "MANUAL_VIEW_ADJUSTMENT",
  ACCOUNT_CREATED: "ACCOUNT_CREATED",
  ACCOUNT_UPDATED: "ACCOUNT_UPDATED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT"
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
